; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30151.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?NewCharArray@@YAPEAD_K@Z			; NewCharArray
PUBLIC	?FreeCharArray@@YAXPEAD@Z			; FreeCharArray
PUBLIC	??_C@_05NAOIJFC@Error@				; `string'
PUBLIC	??_C@_0BJ@LFBPMJAD@Memory?5allocation?5failed@	; `string'
EXTRN	__imp_HeapAlloc:PROC
EXTRN	__imp_HeapFree:PROC
EXTRN	__imp_GetProcessHeap:PROC
EXTRN	__imp_MessageBoxA:PROC
;	COMDAT pdata
pdata	SEGMENT
$pdata$?NewCharArray@@YAPEAD_K@Z DD imagerel $LN5
	DD	imagerel $LN5+71
	DD	imagerel $unwind$?NewCharArray@@YAPEAD_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?FreeCharArray@@YAXPEAD@Z DD imagerel $LN6
	DD	imagerel $LN6+39
	DD	imagerel $unwind$?FreeCharArray@@YAXPEAD@Z
pdata	ENDS
;	COMDAT ??_C@_0BJ@LFBPMJAD@Memory?5allocation?5failed@
CONST	SEGMENT
??_C@_0BJ@LFBPMJAD@Memory?5allocation?5failed@ DB 'Memory allocation fail'
	DB	'ed', 00H					; `string'
CONST	ENDS
;	COMDAT ??_C@_05NAOIJFC@Error@
CONST	SEGMENT
??_C@_05NAOIJFC@Error@ DB 'Error', 00H			; `string'
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?FreeCharArray@@YAXPEAD@Z DD 020a01H
	DD	03006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?NewCharArray@@YAPEAD_K@Z DD 020601H
	DD	030023206H
xdata	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?FreeCharArray@@YAXPEAD@Z
_TEXT	SEGMENT
array$ = 48
?FreeCharArray@@YAXPEAD@Z PROC				; FreeCharArray, COMDAT
; File C:\Users\Admin\Desktop\crackme-native\src\lib.cpp
; Line 14
$LN6:
; Line 15
	test	rcx, rcx
	je	SHORT $LN4@FreeCharAr
	push	rbx
	sub	rsp, 32					; 00000020H
; Line 14
	mov	rbx, rcx
; Line 16
	call	QWORD PTR __imp_GetProcessHeap
	mov	r8, rbx
	xor	edx, edx
	mov	rcx, rax
	call	QWORD PTR __imp_HeapFree
; Line 18
	add	rsp, 32					; 00000020H
	pop	rbx
$LN4@FreeCharAr:
	ret	0
?FreeCharArray@@YAXPEAD@Z ENDP				; FreeCharArray
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?NewCharArray@@YAPEAD_K@Z
_TEXT	SEGMENT
size$ = 48
?NewCharArray@@YAPEAD_K@Z PROC				; NewCharArray, COMDAT
; File C:\Users\Admin\Desktop\crackme-native\src\lib.cpp
; Line 3
$LN5:
	push	rbx
	sub	rsp, 32					; 00000020H
	mov	rbx, rcx
; Line 5
	call	QWORD PTR __imp_GetProcessHeap
	mov	r8, rbx
	mov	edx, 8
	mov	rcx, rax
	call	QWORD PTR __imp_HeapAlloc
; Line 6
	test	rax, rax
	jne	SHORT $LN2@NewCharArr
; Line 8
	lea	r9d, QWORD PTR [rax+16]
	xor	ecx, ecx
	lea	r8, OFFSET FLAT:??_C@_05NAOIJFC@Error@
	lea	rdx, OFFSET FLAT:??_C@_0BJ@LFBPMJAD@Memory?5allocation?5failed@
	call	QWORD PTR __imp_MessageBoxA
; Line 9
	xor	eax, eax
$LN2@NewCharArr:
; Line 12
	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
?NewCharArray@@YAPEAD_K@Z ENDP				; NewCharArray
_TEXT	ENDS
END
